# -*- coding: utf-8 -*-
{
    'name': 'Studio customizations',
    'version': '12.0.1.0',
    'category': 'Studio',
    'description': u"""
This module has been generated by Odoo Studio.
It contains the apps created with Studio and the customizations of existing apps.
""",
    'author': 'GRUPO INDUSTRIAL MEXICANO BIBO SA DE CV',
    'depends': [
        'account',
        'account_cancel',
        'base',
        'bibo-reporte-cotizacion',
        'bibo-reporte-unificado',
        'bibo_module',
        'crm',
        'mrp',
        'product',
        'purchase',
        'sale',
        'stock',
        'web_studio',
    ],
    'data': [
        'data/ir_model_fields.xml',
        'data/ir_ui_view.xml',
        'data/ir_actions_report.xml',
    ],
    'application': False,
    'license': 'OPL-1',
}
